version: '3.8'
services:
  app:
    build:
      context: ./ObjectRelations
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://test_user:1%eKoe736@db:3306/eptlabs_test
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=test_user
      - DB_PASSWORD=1%eKoe736
      - DB_NAME=eptlabs_test
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1%eKoe736
      - MYSQL_DATABASE=eptlabs_test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=1%eKoe736
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed_data.sql:/docker-entrypoint-initdb.d/02_seed.sql

volumes:
  db_data:
